### ISSUE TITLE
2.0: UI - Spamming adding node button adds many a node

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1046]
![Screen Shot 2018-11-28 at 8:40 PM](http://marker.screenshots.prod.s3.amazonaws.com/2726f11dfefd49d4b4039948a39b0ace-1543437657571.png)

**Summary:**
When adding a node to an existing cluster, you are able to spam the 'finish' button. However, how many times you click the button is how many nodes it will  add to the cluster.

**Steps to Reproduce:** 
1. Create a cluster
2. Add a node
3. While the 'finish' button is rotating, continue to spam the heck out of the button. As Bob Ross would say, 'Beat the devil out of it'
4. Check your sg logs and you will see many nodes being spun up.

**Expected Results:** 
Clicking the 'finish' button only allows the amount of nodes the user selected to be added to the cluster.
**Actual Results:** 
Happy little nodes

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/400915ec/add-node](http://localhost:4200/clusters/400915ec/add-node)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1537 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by nikage** [comment]
fixed in https://github.com/supergiant/control/pull/1107

**Comment by gopherstein** [comment]
@nikage #1106 does not appear to fix this. Is this the correct pull?

**Comment by gopherstein** [comment]
duplicate. https://github.com/supergiant/control/issues/1066

**Comment by gopherstein** [comment]
@josephkane @nikage What is the status on this one. Does this need to be a back-end fix?

**Comment by gopherstein** [comment]
This appears to be resolved. It seems that a backend fix may have resolved it. Please re-open if we see this again.
