### ISSUE TITLE
2.0: UI - Analyze icon in Service Catalog is missing Supergiant

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1077]
![Screen Shot 2018-11-30 at 3:32 PM](http://marker.screenshots.prod.s3.amazonaws.com/97a457c4a99742e39768a71672294ea5-1543591963773.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>Zoom Level</strong></td><td>250%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@5x</td></tr></table>

**Comment by hetmanchuk** [comment]
All logotypes imported from github. 

@taaraora , please change this img URL in https://github.com/supergiant/analyze/blob/master/helm/analyze/Chart.yaml from "https://user-images.githubusercontent.com/2936828/48134724-83961d80-e2a3-11e8-89ca-18b11a548c7f.png" to "https://user-images.githubusercontent.com/2936828/48772107-0b305300-eccc-11e8-8c72-4bcbd737226b.png" 
<img width="1013" alt="analyze_chart_yaml_at_master_ _supergiant_analyze" src="https://user-images.githubusercontent.com/11389252/49438280-975f7180-f7c6-11e8-9b98-a70768b03609.png">

@gopherstein please re-assign to @taaraora

**Comment by taaraora** [comment]
PR with fix - https://github.com/supergiant/charts/pull/2

**Comment by gopherstein** [comment]
This is now fixed.

**Comment by hetmanchuk** [comment]
@gopherstein @taaraora In **Chart.yaml** is still the same URL to the broken image: https://github.com/supergiant/analyze/blob/master/helm/analyze/Chart.yaml

Or it will take some time to update?

**Comment by taaraora** [comment]
please merge https://github.com/supergiant/charts/pull/2

**Comment by gopherstein** [comment]
merged.
